name: beauty_spot_lite
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'
 
dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.0.0
  lucide_icons: ^0.257.0
  provider: ^6.0.0
  shared_preferences: ^2.0.0
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

linter:
  rules:
    prefer_const_constructors: true

flutter:
  uses-material-design: true
  assets:
    - assets/mobi1.jpg
    - assets/mobi2.jpg
    - assets/mobi3.jpg
    - assets/mobi4.jpg
    - assets/mobi5.jpg
    - assets/mobi6.jpg
    - assets/mobi7.jpg
    - assets/mobi8.jpg
    - assets/mobi9.jpg
    - assets/mobi10.jpg
    - assets/mobi11.jpg
    - assets/mobi12.jpg
